### ISSUE TITLE
Изменения в Положениях 2023-02-01

### ISSUE THREAD

**Issue by Nevseros** [TimWCA/wca-regulations-translations#115]
Для удобства - полный список того, что меняется в Положениях на 2023. Если очень хочется, можно для каждого пункта отдельную issue создать, но мне лень и нравится так.

- [x] Разрешение на установление и суммарного, и обычного лимита одновременно ([коммит](https://github.com/thewca/wca-regulations/commit/b492c55bf81c35746947ba72cf9d163a6af9ab91))
- [x] Изменения в 2j и 2k, связанные с дисквалификациями ([коммит](https://github.com/thewca/wca-regulations/commit/efc51138858e479dc384f112c3721aa9aadc6057))
- [x] Добавление упоминания логотипа в B1+ ([коммит](https://github.com/thewca/wca-regulations/commit/b4605e80e1a3c44c54c19c19a8d5bbb079898b2e))
- [x] Добавление возможности дисквалификации с одной или нескольких дисциплин в 1f и 1e ([коммит](https://github.com/thewca/wca-regulations/commit/a6f0dd82e5cbf35a2942052b96c19a4c7d1d0fe7))
- [x] Расширение 2s ([коммит](https://github.com/thewca/wca-regulations/commit/0bae4c66b758e1a4202a28d6ef8a7beacf801536))
- [x] `Должен` $\rightarrow$ `следует` в 2k6 ([коммит](https://github.com/thewca/wca-regulations/commit/8e95ca150b503563f8275e07ee3dabc92b9f7dc1))
- [x] Уточнения по запуску и остановке таймера в статье B ([коммит](https://github.com/thewca/wca-regulations/commit/d6935fab6ca1ce3cf44abc501e02d6beeb92ab33))
- [x] Исправления по использованию определений, связанных с таймерами ([коммит](https://github.com/thewca/wca-regulations/commit/3e0f821c2b427ec97883d9151a77f8a1603d4079))
- [x] Удаление Gen 2 из списка разрешённых таймеров ([коммит](https://github.com/thewca/wca-regulations/commit/cf7ebe33cddbab7e185e659a3120338b5ded444d))
- [x] Изменения в 9f4+ ([коммит](https://github.com/thewca/wca-regulations/commit/b7a6ede9754c216e7610e14bf45d3faa91d59c02))
- [x] Изменения в A7a ([коммит](https://github.com/thewca/wca-regulations/commit/0ea793e002ae65846bf5401421567ee6ad189a48))
- [x] Добавление ранее убранного дополнения A1a2+++++ ([коммит первый](https://github.com/thewca/wca-regulations/commit/eef9bfe4853acbc7d5bd7e811d3042e98f226b04), [коммит второй](https://github.com/thewca/wca-regulations/commit/85ccbbc1fd997696f634b4cfd5c8c20a3b321500), [коммит третий](https://github.com/thewca/wca-regulations/commit/ea75946fb7444ea81bf31d2f3f6c844d2ec7cf91))
- [x] Добавление штрафа в 2i ([коммит](https://github.com/thewca/wca-regulations/commit/c9966e8fcd5b0e734d09cd6fbc9383323bbc6150))
- [x] Капитализация X и Y, используемых как переменные ([коммит](https://github.com/thewca/wca-regulations/commit/d8ecea39fc9a1e6187e2e774fce09280be297079))
- [x] Изменение формулировки 2i1c+ ([коммит](https://github.com/thewca/wca-regulations/commit/0ab3b0dd364ddb4b8b99c373d2d186968fc7f51b))
- [x] Уточнение A7g ([коммит](https://github.com/thewca/wca-regulations/commit/30f57df2a1c46a296335ed65df3f350bdf3a6be0))
- [x] Остановка попытки сразу после нарушения положения, ведущего к её дисквалификации ([коммит](https://github.com/thewca/wca-regulations/commit/561463d03d599f2d507d1f4fc6ad6fc866502ed9))
- [x] Расширение 2a3 ([коммит](https://github.com/thewca/wca-regulations/commit/1c48362ee4b33709ed0dda8d813b9b240d97743e))
- [x] Определение окончания соревнований ([коммит](https://github.com/thewca/wca-regulations/commit/49a4ed65046f8c7d80e3465b288f305712282baf))
- [x] Добавление уточнения для попыток, когда судья забывает установить непрозрачный объект в слепой сборке ([коммит](https://github.com/thewca/wca-regulations/commit/ada6a1684533b2a8bcc8864a678feed214ad085d))
- [x] Добавление уточнения по записи результата Мульти-блайнда ([коммит](https://github.com/thewca/wca-regulations/commit/883ca14911f675063adcda80f0ff97a949236f3e))
- [x] Определение хода ([коммит](https://github.com/thewca/wca-regulations/commit/e2530fc76e09fc18f8565a033572b1b1f3a35242))
- [x] Уточнение об общении с делегатом WCA и судьёй во время попытки Сборки на количество ходов ([коммит](https://github.com/thewca/wca-regulations/commit/750d1a63e6263ffd6777b605140f6128d515152d))
- [x] Добавление исключения в 9l ([коммит](https://github.com/thewca/wca-regulations/commit/e7047a05ed15faf772388708f8fa92e55feebab5))
- [x] Изменения в 11e++... ([коммит](https://github.com/thewca/wca-regulations/commit/4d4a6da5104196e24f09519e60611a58b8378a0d))
- [x] Добавление кнопок Clock в 4g2 ([коммит](https://github.com/thewca/wca-regulations/commit/4c3f0a7c6c0121b2b2f75dbed636ab8e36b71972))
- [x] Разрешение более позднего или раннего участия - добавление 1h+++ ([коммит](https://github.com/thewca/wca-regulations/commit/896f3984f16daa2ebf9773045996ab07c90adb71), [коммит](https://github.com/thewca/wca-regulations/commit/0422515cf158f3691522804c707687b6e0735020))
- [x] Clock ([коммит](https://github.com/thewca/wca-regulations/commit/9c95b38a52a15bc3c21b35c97aea97ef6ca988e7))
- [x] Определение элемента в 5b6 ([коммит](https://github.com/thewca/wca-regulations/commit/f5d19c6bdaced44780b9df9b2ae066f98d1029d7))

Ещё не финализированные изменения и формулировки (буду обновлять и перетаскивать вверх по мере того, как они будут залиты):

Не осталось!

Развлекаемся, мальчики!

**Comment by AlexKatyukov** [comment]
Предлагаю тыкать галочки, когда создан соответствующий PR, мы уже не потеряем пунктик)

**Comment by AlexKatyukov** [comment]
Коллеги, всё сделано, осталось доработать 👩‍🏭👩‍🏭👩‍🏭
