### ISSUE TITLE
Некорректный перевод 3l

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#18]
`3l) Головоломки могут иметь максимум один логотип на наклейке/пластинке. Исключение: для сборок вслепую головоломки не должны иметь логотип.`

Данный перевод может быть воспринят как "на каждой наклейке/пластинке может быть максимум один логотип"
Оригинал: 

`3l) A puzzle may have a logo on a colored part. If it does, it must have at most one colored part with a logo. Exception: For blindfolded events, a puzzle must not have a logo.`

**Comment by Nevseros** [comment]
Еще кажется, что лучше перевести не "на наклейке/пластинке", а "на цветной части": 3d говорит о четырех видах цветных частей, а тут названы только две из них.

**Comment by AlexKatyukov** [comment]
```
Головоломки могут иметь максимум одну цветную часть с логотипом. Исключение: для сборок вслепую головоломки не должны иметь логотип.
```
