### ISSUE TITLE
Не хватает двоеточия в E2a

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#22]
`E2a) Судья раздаёт скрамблы и бумагу всем участникам. Судья затем запускает секундомер и говорит "Начали".`

Перед `"Начали"` должно быть двоеточие

**Comment by AlexKatyukov** [comment]
Возможно, тема для отдельного issue, но что вы думаете по поводу кавычек? Может быть, мы уже доросли до «кавычек-ёлочек»?

**Comment by Niksson** [comment]
> Возможно, тема для отдельного issue, но что вы думаете по поводу кавычек? Может быть, мы уже доросли до «кавычек-ёлочек»?

Лучше создать отдельный тред

**Comment by Niksson** [comment]
#41
