### ISSUE TITLE
Странный перевод A7c+

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#29]
`A7c+) ДОПОЛНЕНИЕ Если результат, подписанный участником, неполный или плохо читаемый, то он интерпретируется самым худшим способом (например, "1:05" будет рассматриваться как 1:05.99, "25.X3" будет рассматриваться как 25.73, если X похожа на цифру 1 или 7). Так как дисплей стакмата показывает время X:0Y.ss как X:Y.ss, то отсутствие цифры десятков секунд будет интерпретироваться c большей вероятностью, чем отсутствие единиц (например, "1:2.27" будет рассматриваться как 1:02.27). Судья, подписавший попытку, может быть вызван для уточнения результата на усмотрение человека, заносящего результаты в компьютер.`

Оригинал:

`A7c+) ADDITION If a result signed by a competitor is found to be incomplete or unreadable, it should be interpreted the worst reasonable way (e.g. "1:05" will be considered 1:05.99, "25.X3" will be considered 25.73 if X could be either a 1 or a 7). Given that the Stackmat timer displays a time of X:0Y.ss as X:Y.ss, a missing tens digit should be considered more likely than a missing ones digit (e.g. "1:2.27" will be considered 1:02.27). The judge who signed an ambiguous result may be requested to clarify it, at the discretion of the score taker.`

Здесь стоит подумать над переделкой перевода

**Comment by Nevseros** [comment]
Возможно:
... Так как дисплей стакмата показывает время X:0Y.ss как X:Y.ss, то результат будет интерпретироваться как не содержащий цифру десятков секунд с большей вероятностью, чем не содержащий единиц (напимер...

**Comment by Niksson** [comment]
Полная формулировка:
```
A7c+) ДОПОЛНЕНИЕ Если результат, подписанный участником, неполный или плохо читаемый, то он интерпретируется самым худшим способом (например, "1:05" будет рассматриваться как 1:05.99, "25.X3" будет рассматриваться как 25.73, если X похожа на цифру 1 или 7). Так как дисплей стакмата показывает время X:0Y.ss как X:Y.ss, если результат записан как X:Y.ss, то это следует воспринимать как отсутствующее количество десятков секунд, нежели отсутствующее количество целых секунд (например, "1:2.27" будет рассматриваться как 1:02.27). Судья, подписавший попытку, может быть вызван для уточнения результата на усмотрение человека, заносящего результаты в компьютер.
```

**Comment by Nevseros** [comment]
> Полная формулировка:
> 
> ```
> A7c+) ДОПОЛНЕНИЕ Если результат, подписанный участником, неполный или плохо читаемый, то он интерпретируется самым худшим способом (например, "1:05" будет рассматриваться как 1:05.99, "25.X3" будет рассматриваться как 25.73, если X похожа на цифру 1 или 7). Так как дисплей стакмата показывает время X:0Y.ss как X:Y.ss, если результат записан как X:Y.ss, то это следует воспринимать как отсутствующее количество десятков секунд, нежели отсутствующее количество целых секунд (например, "1:2.27" будет рассматриваться как 1:02.27). Судья, подписавший попытку, может быть вызван для уточнения результата на усмотрение человека, заносящего результаты в компьютер.
> ```

Добавила бы `вероятнее` и `как`:
`то это следует воспринимать как отсутствующее количество десятков секунд вероятнее, нежели как отсутствующее количество целых секунд`

**Comment by Nevseros** [comment]
У нас там еще и displays вылилось в дисплей, хотя тут явно глагол. 
```
Если результат, подписанный участником, неполный или плохо читаемый, то он интерпретируется самым худшим способом (например, «1:05» будет рассматриваться как 1:05.99, «25.X3» будет рассматриваться как 25.73, если X похожа на цифру 1 или 7). Так как таймер стакмата показывает время X:0Y.ss как X:Y.ss, то это следует воспринимать как отсутствующее количество десятков секунд, а не как отсутствующее количество целых секунд (например, «1:2.27» будет рассматриваться как 1:02.27). Судья, подписавший попытку, может быть вызван для уточнения результата на усмотрение человека, заносящего результаты в компьютер.
```
