### ISSUE TITLE
Странный перевод 4b3e

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#30]
`4b3e) Кубы 5x5x5, 6x6x6, 7x7x7, а также Мегаминкс: достаточно много случайных движений (вместо случайного состояния), для сборки из которого необходимо не менее 2 ходов.`

Оригинал:

`4b3e) 5x5x5 Cube, 6x6x6 Cube, 7x7x7 Cube, and Megaminx: sufficiently many random moves (instead of random state), at least 2 moves to solve.`

**Comment by Nevseros** [comment]
Возможно:
... много случайных движений (вместо случайного состояния), чтобы для сборки было необходимо не менее 2 ходов.

**Comment by Niksson** [comment]
Я бы оставил перевод как он есть

**Comment by Nevseros** [comment]
> Я бы оставил перевод как он есть

Отбрасываем скобки и читаем, что получается. Выходит грамматическая ошибка в построении сложноподчинённого предложения - в самом предложении без уточнения в скобках нет ничего, к чему бы могло относиться `которого`.

**Comment by AlexKatyukov** [comment]
Я с 10-го раза понял, в чём проблема. Убрал «палец вниз», поставил «палец вверх» Катиному предложению.
