### ISSUE TITLE
Сомнительный перевод 4d4

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#31]
`4d4) Перемешивание Clock'а начинается с любой из двух сторон, все циферблаты указывают на 12 часов.`

Оригинал:

`4d4) Clock is scrambled starting with either side in front and 12 o'clock pointing up.`

Русский перевод по сути говорит просто о собранном состоянии головоломки (что уже требует при сдаче положение А2а), тогда как оригинал говорит именно об ориентации.

**Comment by iandashevskyi** [comment]
Может быть "Перемешивание Clock'а начинается  в положении любой стороной вверх( или вперёд?), все циферблаты указывают на 12 часов."?

**Comment by Nevseros** [comment]
> Может быть "Перемешивание Clock'а начинается в положении любой стороной вверх( или вперёд?), все циферблаты указывают на 12 часов."?

Изначально загвоздка именно в том, что не любой наверх, а 12-ю часами наверх.

**Comment by Nevseros** [comment]
Возможно:
"Перемешивание Clock'а начинается с любой из двух сторон, 12 часов располагаются сверху [или указывают наверх]."

**Comment by AlexKatyukov** [comment]
```
Перемешивание Clock'а начинается с любой из двух сторон, 12 часов направлены вверх
```

**Comment by Niksson** [comment]
`Перемешивание Clock'а начинается с любой из двух сторон, указатели 12 часов направлены вверх`
