### ISSUE TITLE
Некорректное определение в C1b4

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#32]
`C1b4) Во время сборки участник может держать головоломку на поверхности стола для удобства (см. Положение 7f1d).`

Оригинал:

`C1b4) During the solve, the competitor may hold the puzzle against the surface to help operate the puzzle (see Regulation 7f1d).`

Определение в `7f1d`:
`7f1d) Поверхность: плоская поверхность, на которой располагается стакмат. Мат считается частью поверхности. Таймер не считается частью поверхности.`

**Comment by TimWCA** [comment]
Тут, может, в 7f1d написать "поверхность стола"? Понятнее будет.
