### ISSUE TITLE
Соглашение по использованию слова "Положение"

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#34]
В оригинале слово "Regulation" и "Regulations" пишутся с заглавной буквы. Необходимо выработать соглашению по написанию перевода этого слова ("Положение"/"Положения") с заглавной или со стройной буквы

**Comment by AlexKatyukov** [comment]
Несмотря на мою любовь к строчному «делегат», «Положения», имхо, с заглавной.

**Comment by TimWCA** [comment]
Я всегда с заглавной пишу, да и в переводе вроде всегда так до этого писали
