### ISSUE TITLE
Лишняя запятая в E2d1

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#35]
`E2d1) Решение должно состоять не более, чем из 80 ходов (включая повороты головоломки целиком), посчитанные в метрике движений при выполнении сборки (см. Положение 12a6). Наказание: дисквалификация попытки (DNF).`

Запятая между "более" и "чем" не нужна

**Comment by TimWCA** [comment]
Сейчас исправлю
