### ISSUE TITLE
Некорректный перевод A6d

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#37]
`A6d) Участник должен останавливать таймер обеими руками, держа ладони прямо и вниз. Штраф: +2 секунды.`

Оригинал:

`A6d) The competitor must stop the timer using both hands, placed flat on the sensors with palms down. Penalty: time penalty (+2 seconds).`

Нет упоминания, что руки должны касаться сенсоров

**Comment by Nevseros** [comment]
Заново открываю после обсуждения этого положения с носителем. 

Наша проблема в том, что мы `hand` переводим как `рука`, но на самом деле это часть от запястья до кончиков пальцев. Нужно руки как-то адекватно заменить на правильный перевод, чтобы никаких остановок запястьями по нашему переводу быть не могло.

Предложено `кисть`.

**Comment by AlexKatyukov** [comment]
*«Останавливай хоть локтями, но ладонями вниз»* (с) один Д/делегат WCA.

`Участник должен останавливать таймер касаясь сенсоров таймера стакмата кистями обеих рук, держа ладони прямо и вниз. Штраф: +2 секунды.`

**Comment by Nevseros** [comment]
Просто хочу подчеркнуть, что подлежащих замене `hand` 11 штук в Положениях, ещё несколько в Дополнениях.
