### ISSUE TITLE
Сомнительный перевод 3l2

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#38]
`3l2) The logo may be embossed, engraved, or consist of an overlay sticker.`

Словосочетание `overlay sticker` довольно сложно перевести на русский, в итоге мы имеем это:

`3l2) Логотип может быть рельефным, выгравированным или иметь два слоя наклеек.`

По возможности следует исправить это на что-то более благозвучное

**Comment by AlexKatyukov** [comment]
... или быть наклйкой, наклеенной поверх основной наклейки.
(возможно)

**Comment by Nevseros** [comment]
> 

Наклейка поверх именно наклейки точно не должно быть - цветная часть не обязательно наклейка.
Возможно:
... или быть наклейкой, наклеенной поверх цветной части.

**Comment by Niksson** [comment]
Вообще, переводчик выдает сочетание "оверлейная наклейка". Я поискал его в поиске - оно действительно используется, в том числе в типографиях. Возможно, стоит прямо так его и задействовать?

**Comment by TimWCA** [comment]
Может:
`3l2) Логотип может быть рельефным, выгравированным или наклеенным на цветную часть.`?

**Comment by TimWCA** [comment]
Вариант DeepL Translate:
`Логотип может быть рельефным, выгравированным или представлять собой наклейку.`

**Comment by Niksson** [comment]
> > 
> 
> Наклейка поверх именно наклейки точно не должно быть - цветная часть не обязательно наклейка. Возможно: ... или быть наклейкой, наклеенной поверх цветной части.

Тогда мне кажется, лучше, например, так
```
Логотип может быть рельефным, выгравированным или представлять собой прозрачную наклейку с изображением логотипа, наклеенную на цветную часть
```

**Comment by AlexKatyukov** [comment]
Почему прозрачную?) Наклейку того же цвета или другого, но не полностью загораживающую цвет ~наклейки~ цветной части?

**Comment by Nevseros** [comment]
> Почему прозрачную?) Наклейку того же цвета или другого, но не полностью загораживающую цвет ~наклейки~ цветной части?

Полагаю, потому что если вбить именно overlay sticker в гугл, выходят штучки без фона, то бишь прозрачные.
