### ISSUE TITLE
Наименование команды WCA

### ISSUE THREAD

**Issue by AlexKatyukov** [TimWCA/wca-regulations-translations#40]
`2c2) Участники, участвовавшие ранее в соревнованиях, должны предоставлять личную информацию, согласующуюся с информацией, указанной в профиле WCA. Если участник хочет изменить или обновить личные данные вне соревнований (например, при изменении гражданства, имени или пола), то он должен связаться с Командой WCA, занимающейся результатами`

Тут, скорее, ко мне, потому что это изменение в ленги сайта, но мне очень не нравится, что `WCA Results Team` переводится как `Команда WCA, занимающаяся результатами`.

Думаю привести к `Команда Результатов WCA`, чтобы было похоже на другие [на этой странице](https://www.worldcubeassociation.org/teams-committees).

Однако, если заменим ленг на сайте, то нужно и в перевод Положений внести, так что пишу :)

**Comment by AlexKatyukov** [comment]
https://github.com/thewca/worldcubeassociation.org/pull/6595

Внёс PR в репозиторий сайта WCA.

@Niksson, @TimWCA, ваш ход :)

**Comment by TimWCA** [comment]
> https://github.com/thewca/worldcubeassociation.org/pull/6595
> 
> Внёс PR в репозиторий сайта WCA.
> 
> @Niksson, @TimWCA, ваш ход :)

Как именно сделал? Команда результатов WCA?

**Comment by AlexKatyukov** [comment]
`Команда Результатов WCA`

**Comment by TimWCA** [comment]
> `Команда Результатов WCA`

Значит надо в Положениях поменять?
