### ISSUE TITLE
Использование «» вместо ""

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#41]
Поступило предложение использовать кавычки-ёлочки вместо кавычек обычных.

Нужно мнение

**Comment by AlexKatyukov** [comment]
http://new.gramota.ru/spravka/letters/89-kav — технически, в компьютерных текстах можно и "компьютерные кавычки", но не вижу ничего суперсложного в «кавычках-ёлочках», а текст читается гораздо приятнее, на мой взгляд.

**Comment by Niksson** [comment]
> http://new.gramota.ru/spravka/letters/89-kav — технически, в компьютерных текстах можно и "компьютерные кавычки", но не вижу ничего суперсложного в «кавычках-ёлочках», а текст читается гораздо приятнее, на мой взгляд.

Как их набирать в текстовом редакторе (не Word), чтобы не сломать пальцы?

**Comment by AlexKatyukov** [comment]
Я привык не ломать через Alt-code Alt+0171 « и Alt+187 ».

Но раньше в таких случаях использовал ctrl+c, ctrl+v.

Если вы не против, но вам лень, могу сделать PR с именно «ёлочным» изменением.

**Comment by Niksson** [comment]
@TimWCA, что думаешь?

**Comment by TimWCA** [comment]
Ну вообще по русским правилам типографики надо "ёлочки". Можно просто через "найти и заменить" всё разом сделать. Могу сделать PR

**Comment by Niksson** [comment]
> Ну вообще по русским правилам типографики надо "ёлочки". Можно просто через "найти и заменить" всё разом сделать. Могу сделать PR

Ну ты разом заменишь все " на что-то одно. Но если ты знаешь быстрый способ заменить, то было бы неплохо

**Comment by AlexKatyukov** [comment]
Регулярочки, но ради всего святого, аккуратнее :)
А то в языке бывают всякие конструкции из кавычек в кавычках.

**Comment by TimWCA** [comment]
> Регулярочки, но ради всего святого, аккуратнее :)
> А то в языке бывают всякие конструкции из кавычек в кавычках.

Ну в положениях я такого не видел
