### ISSUE TITLE
Автоматическая проверка лейблов в Дополнениях

### ISSUE THREAD

**Issue by AlexKatyukov** [TimWCA/wca-regulations-translations#52]
Например, в E2c2++) в оригинале `Reminder`, а у нас `Дополнение` вместо `Напоминание`.

Стоит автоматически проверить на соответствие
| Оригинал | Перевод |
| --- | --- |
| ADDITION | ДОПОЛНЕНИЕ |
| CLARIFICATION | УТОЧНЕНИЕ |
| EXPLANATION | ОБЪЯСНЕНИЕ |
| RECOMMENDATION | РЕКОМЕНДАЦИЯ |
| REMINDER | НАПОМИНАНИЕ |
| EXAMPLE | ПРИМЕР |

**Comment by AlexKatyukov** [comment]
P.S. Могу сделать я, если поставите Assignee, чтобы не забыл :)

**Comment by TimWCA** [comment]
> Например, в E2c2++) в оригинале `Reminder`, а у нас `Дополнение` вместо `Напоминание`.
> 
> Стоит автоматически проверить на соответствие
> 
> Оригинал	Перевод
> ADDITION	ДОПОЛНЕНИЕ
> CLARIFICATION	УТОЧНЕНИЕ
> EXPLANATION	ОБЪЯСНЕНИЕ
> RECOMMENDATION	РЕКОМЕНДАЦИЯ
> REMINDER	НАПОМИНАНИЕ
> EXAMPLE	ПРИМЕР

У нас в E2c2 вообще всё неправильно было :)

**Comment by AlexKatyukov** [comment]
Проверено, всё в порядке
