### ISSUE TITLE
Уточнение в 3d1b+

### ISSUE THREAD

**Issue by Nevseros** [TimWCA/wca-regulations-translations#53]
Русскоязычный перевод: 

`3d1b+) УТОЧНЕНИЕ Шаблоны могут быть не на каждой стороне, но если на какой-либо стороне есть хотя бы одна цветная часть с шаблоном, то все цветные части на этой стороне должны иметь такой же шаблон. Элементы не должны иметь никаких особенностей (например, текстуры или неровность шаблона), которые существенно отличают их от других похожих элементов.`

Оригинал:

`3d1b+) CLARIFICATION Patterns do not need to be present on every face, but only on faces where a distinct color cannot be found. Pieces must not have any features (e.g. textures, pattern irregularities) that significantly distinguish them from similar pieces.`

В оригинале нет части "но если на какой-либо стороне есть хотя бы одна цветная часть с шаблоном, то все цветные части на этой стороне должны иметь такой же шаблон". Не искажает, но нужно ли, если нет в оригинале?

**Comment by Niksson** [comment]
Возможно, было упущено изменение этого положения.

Я бы предложил вариант:
`3d1b+) УТОЧНЕНИЕ Шаблоны могут быть не на каждой стороне, а только на тех, чьи цвета невозможно различить. Элементы не должны иметь никаких особенностей (например, текстуры, неровность шаблона), которые существенно отличают их от других похожих элементов.`

**Comment by Nevseros** [comment]
> Возможно, было упущено изменение этого положения.
> 
> Я бы предложил вариант: `3d1b+) УТОЧНЕНИЕ Шаблоны могут быть не на каждой стороне, а только на тех, чьи цвета невозможно различить. Элементы не должны иметь никаких особенностей (например, текстуры, неровность шаблона), которые существенно отличают их от других похожих элементов.`

Мне почему-то не нравится "чьи" в отношении к "стороне". Может "... а только на тех, цвета которых невозможно различить."?

**Comment by Niksson** [comment]
> > Возможно, было упущено изменение этого положения.
> > Я бы предложил вариант: `3d1b+) УТОЧНЕНИЕ Шаблоны могут быть не на каждой стороне, а только на тех, чьи цвета невозможно различить. Элементы не должны иметь никаких особенностей (например, текстуры, неровность шаблона), которые существенно отличают их от других похожих элементов.`
> 
> Мне почему-то не нравится "чьи" в отношении к "стороне". Может "... а только на тех, цвета которых невозможно различить."?

Если это грамматически более правильно, то возможно, это будет лучше
