### ISSUE TITLE
"Inspection" -> "Преинспекция" или "Инспекция"?

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#64]
В переводе положений используется слово "преинспекция". Есть ли смысл поменять это на слово "инспекция" в переводе?

**Comment by Nevseros** [comment]
Тоже не нравится "преинспекция", да и больше слышу, что говорят "инспекция".

**Comment by TimWCA** [comment]
В оригинале «Инспекция». Откуда это «пре-» взялось? :)
