### ISSUE TITLE
Недоперевод 9b4b

### ISSUE THREAD

**Issue by AlexKatyukov** [TimWCA/wca-regulations-translations#74]
`Best of X` вместо `Лучшее из X`

**Comment by AlexKatyukov** [comment]
(дополнительно стоит пройтись поиском по `Best`, `Mean` и `Average`)

UPD: проверил, это единственное такое место

**Comment by Nevseros** [comment]
Дубликат #69 :)

**Comment by AlexKatyukov** [comment]
_Just for information: Тимофей попросил добавить ишью во время собеса, когда пытался чёт найти в Положениях._
