### ISSUE TITLE
Антирусский язык в 4b2a

### ISSUE THREAD

**Issue by AlexKatyukov** [TimWCA/wca-regulations-translations#75]
[Ссылка на пункт](https://www.worldcubeassociation.org/regulations/translations/russian/#4b2a)

Мне не нравится формулировка `Делегат WCA, назначенный для соревнования`. Я бы предпочёл вместо неё `Делегат WCA, назначенный на соревнования`. Возможно, без запятой, тут не уверен.

**Comment by Nevseros** [comment]
LGTM. Запятая нужна, причастный оборот после определяемого слова.

**Comment by Nevseros** [comment]
[1c++](https://www.worldcubeassociation.org/regulations/translations/russian/guidelines.html#1c++)  сюда же.
