### ISSUE TITLE
Таймер стакмата — ?

### ISSUE THREAD

**Issue by AlexKatyukov** [TimWCA/wca-regulations-translations#77]
Мне не нравится словосочетание `Таймер стакмата`. Вообще. Мне кажется, нужно подумать, как это называть. В оригинале это `The timer of the Stackmat`.

Используется в 7f1c, B2f.

Мне кажется, лучше использовать `Таймер Stackmat`, но feel free.

(В #15 уже обсуждалось).

**Comment by Nevseros** [comment]
7f1a - просто `Стакмат` тоже тогда нужно менять на `Stackmat`?

**Comment by AlexKatyukov** [comment]
> 7f1a - просто `Стакмат` тоже тогда нужно менять на `Stackmat`?

Вот тут, имхо, нет. Хотя тогда непонятно... Может, `Таймер Стакмат`?

**Comment by AlexKatyukov** [comment]
[A6b+](https://www.worldcubeassociation.org/regulations/translations/russian/guidelines.html#A6b+)) Значение в 0.06 секунд было выбрано из-за особенностей Stackmat таймеров и их возможных неисправностей.

🤣

**Comment by Niksson** [comment]
Я не вижу проблем в сочетании "таймер стакмата". Это, как мне кажется, единственный не душный вариант указать на то, что это таймер, и что он относится к стакмату, чтобы явно противопоставлять его секундомеру.

**Comment by TimWCA** [comment]
В большинстве мест в оригинале употребляется "Stackmat timer". Там, думаю, можно перевести как "таймер Stackmat". Это же подходит и для выражения "The timer of Stackmat". Думаю, если в 7f1a написать просто "Stackmat" ничего страшного. Мне вообще не нравится, что у нас Stackmat русскими буквами написано) Но это только моё мнение. Clock же по-английски ~~будь он неладен~~ :)

**Comment by AlexKatyukov** [comment]
Словосочетание мне всё ещё не нравится, но я понял, почему оно именно оно.

При изменениях #85 наверное, будет понять ещё проще.

Закрываю, так я прозрел, а вариантов лучше не придумали :)
