### ISSUE TITLE
Добавление ссылки на этот репозиторий

### ISSUE THREAD

**Issue by Nevseros** [TimWCA/wca-regulations-translations#83]
Возможно:

`Вопросы и замечания по поводу перевода отправляйте по электронной почте на [nick.masson@yandex.ru](mailto:nick.masson@yandex.ru) или сообщайте о них [на GitHub](https://github.com/TimWCA/wca-regulations-translations/issues).`

Или:

`Вопросы и замечания по поводу перевода отправляйте по электронной почте на [nick.masson@yandex.ru](mailto:nick.masson@yandex.ru). Также замечания принимаются в [репозитории на GitHub](https://github.com/TimWCA/wca-regulations-translations/issues).`

**Comment by AlexKatyukov** [comment]
Предлагаю ссылку сразу в раздел /issues. У гитхаба для непрошаренных и так не очень понятный интерфейс, а так сразу будет видно, куда замечание «ложить».

Вторая формулировка нравится больше.
