### ISSUE TITLE
"Стакмат", "таймер стакмата", "таймер" в нескольких Положениях

### ISSUE THREAD

**Issue by Nevseros** [TimWCA/wca-regulations-translations#85]
_Ниже все определения и замечания применяются с использованием нынешних формулировок (т.е. "таймер стакмата", "стакмат" и "таймер"). Их переформулировка - отдельная issue (#77)._

[7f1a](https://www.worldcubeassociation.org/regulations/translations/russian/#7f1a) даёт определение `стакмата` как `таймер Speed Stacks Stackmat в комплекте с полноразмерным матом`. `Таймер стакмата` - часть этого самого `стакмата` - есть таймер от Speed Stacks. В некоторых Положениях и Дополнениях к Положениям использовано `стакмат` вместо `таймер стакмата`: 7f3, A1b2, A4d, A6b, B5a, A7c+

В A4b в оригинале в обоих случаях `таймер` (если честно, мне это не нравится, хоть оно и компенсируется другими Положениями), у нас - в одном `таймер`, в другом `стакмат`. B2b также использует `стакмат` в переводе, тогда как в оригинале `таймер`.

В A1b1 вместо просто `стакмат` используется `стакмат и мат` - с точки зрения понимания второй вариант лучше, но первый лучше с точки зрения определений.

В 7f1a также используется `таймер` во втором предложении, в оригинале не используется ничего. Допуская, что внутри самого Положения с определением `стакмата` такое может быть, не переформулировала бы, но as you wish.

7f4, A3b используют также `таймер`, тогда как лучше бы переформулировать на чисто английское название `Generation 5 Pro Timer`.

A7g+ - первый из `таймеров` должен быть заменён на `таймер стакмата`.

Формулировка - другой сложный вопрос в #77. A6b+ там.

**Comment by Niksson** [comment]
Мое мнение:

Хоть 7f1 и дает определения, это не исчерпывающий список. Если используется определение, отличное от указанного в 7f1, то его следует переводить, исходя из контекста, а не определений в 7f1.

По конкретным положениям:

* 7f3: заменить на "таймер стакмата". Здесь используется определение, отличное от указанных в 7f1. В этом и других правилах, где используется сочетание "Stackmat timer" оно используется специально, чтобы противопоставить его секундомеру
* A1b2: аналогично
* A6b: аналогично
* B5a: аналогично
* A4d: здесь интересно. В оригинале имеем текст: `If <a> Stackmat timer is in use, the competitor should keep their hands on <the> timer`. Обратите внимание на артикли. Сначала имеется в виду "некий" таймер стакмата, затем используется артикль "the", указывающий на вышеуказанный таймер стакмата. Технически, это нарушает термин, принятый в 7f1, но семантически читателю должно быть понятно, что имеется в виду. В переводе предлагаю формулировку:
`A4d) Если используется таймер стакмата, то участнику следует держать руки на этом таймере до тех пор, пока не загорится зелёная лампочка...`
* A7c+: "дисплей стакмата" заменить на "дисплей таймера стакмата"
* A4b: здесь оригинал немножко не сходится с собственными определениями, так как таймером может быть и таймер стакмата, и секундомер. Это отдельная проблема, которую можно вынести для WRC. Также меня смущает выражение `the side of the timer that is closer to the competitor`. Для перевода предлагаю следующую формулировку
`A4b) Участник кладёт пальцы рук на сенсорные панели таймера стакмата. Ладони при этом должны быть направлены вниз, находясь на ближней к участнику стороне мата`
* A1b1: в графе исключения "стакмат и мат" можно заменить на просто "стакмат"
* 7f1a: перевод разворачивает строение второго предложения. В оригинале список идет в начале, в переводе - в конце. Я считаю, что это приемлемый вариант. Я предлагаю следующий вариант перевода:
`7f1a) Стакмат: таймер марки Speed Stacks Stackmat в комплекте с полноразмерным матом. Допустимые к использованию модели (можно заменить на слово "версии"): ...`
* 7f4: У меня другое предложение - `7f4) Модель стакмата Generation 5 Pro должна использоваться в режиме "2-Pad mode"`. Аналогично для A3b
* A7g+: Я думаю, что стоит оба вхождения заменить на "таймер стакмата", не только первое

**Comment by Nevseros** [comment]
> A4b: здесь оригинал немножко не сходится с собственными определениями, так как таймером может быть и таймер стакмата, и секундомер. Это отдельная проблема, которую можно вынести для WRC.

Создавала на форуме [тред](https://forum.worldcubeassociation.org/t/a6d-wording/16095) с аналогичной (вроде) неточностью в Положениях, но в A6d. WRC, похоже, хорошо и так. Однако, если посмотреть в саму статью B, на которую ссылался Айван, то [B2b](https://www.worldcubeassociation.org/regulations/#B2b) его ответ косвенно разрушает :(

**Comment by Nevseros** [comment]
#15, кстати, из этой же оперы, но сюда почему-то не вошло. Там тоже нужно заменить `таймер` на  `таймер стакмата`.
