### ISSUE TITLE
Неправильный перевод C1b3

### ISSUE THREAD

**Issue by Niksson** [TimWCA/wca-regulations-translations#91]
Оригинал
```
[C1b3](https://www.worldcubeassociation.org/regulations/#C1b3)) If other body parts of the competitor come in contact with the puzzle or parts of the puzzle without the competitor's intention and without applying moves, this is not considered operating the puzzle, at the discretion of the judge.
```
Перевод
```
[C1b3](https://www.worldcubeassociation.org/regulations/translations/russian/#C1b3)) Если происходит повреждение головоломки и её элементы кратковременно задевают участника помимо его воли, то по решению судьи это за касание не считается.
```

В оригинале нет условия, что произошло повреждения головоломки, "другая часть тела" может войти в контакт как с головоломкой, так и с ее частями.

**Comment by Niksson** [comment]
Здесь еще стоит подумать над определением в C1b. В оригинале используется слово `operate`, в переводе - слово `касаться`, что не одно и то же, под слово `operate` больше подходят `оперирование`, `манипулирование`. Вот только черт знает, как это корректно перевести, чтобы не резало глаз.

**Comment by Nevseros** [comment]
`Воздействовать`, `воздействие`? `Управлять`, `управление`? Ужас один :(. Честно говоря, `воздействовать` мне нравится больше всего.
