### ISSUE TITLE
"Делегат" → "делегат" 

### ISSUE THREAD

**Issue by Nevseros** [TimWCA/wca-regulations-translations#93]
Названия должностей пишутся с маленькой буквы, если это не регламентируется отдельно. Следует заменить во всех положениях.

**Comment by AlexKatyukov** [comment]
Side note от транслятора сайта.

Нужно стремиться к однородности Положений и сайта — как только/ если это улетит в main основного репозитория, нужно будет заменить `Д` на `д` и на страницах сайта. А ещё подумать о названиях команд/комитетов/совета.

**Comment by Nevseros** [comment]
Что именно подразумеваешь под названиями команд/комитетов/совета?

**Comment by AlexKatyukov** [comment]
`Дисциплинарный Комитет WCA` → `Дисциплинарный комитет WCA`

**Comment by TimWCA** [comment]
Ну по идее если делегат WCA — это не высшая государственная должность, то с маленькой :) По поводу комитетов тоже, думаю, с сторочной (кроме первого слова). Едиственный вопрос — (П/п)оложения. Но там, вроде, принято как раз с заглавной.
